AllCops:
  Exclude:
    - 'webinar_ru.gemspec'
    - 'spec/spec_helper.rb'
    - Rakefile
    - bin/*
Metrics/BlockLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Metrics/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*
